In [1]:
import pandas as pd
games = pd.read_csv("VGSales.csv", low_memory=False)
games.head()

,Rank,Nombre,Plataforma,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,90,Pac-Man,2600,1982.0,Puzzle,Atari,7.28,0.45,0.0,0.08,7.81
1,240,Pitfall!,2600,1981.0,Platform,Activision,4.21,0.24,0.0,0.05,4.50
2,259,Asteroids,2600,1980.0,Shooter,Atari,4.00,0.26,0.0,0.05,4.31
3,545,Missile Command,2600,1980.0,Shooter,Atari,2.56,0.17,0.0,0.03,2.76
4,608,Space Invaders,2600,NaN,Shooter,Atari,2.36,0.14,0.0,0.03,2.53

In [2]:
games[games["Rank"] >= 16500]

,Rank,Nombre,Plataforma,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
639,16515,Balloon Pop 2,3DS,2012.0,Puzzle,UFO Interactive,0.01,0.00,0.00,0.0,0.01
640,16531,Kiniro no Corda 3,3DS,2015.0,Adventure,Tecmo Koei,0.00,0.00,0.01,0.0,0.01
641,16538,Mushi Bugyou,3DS,2013.0,Action,Namco Bandai Games,0.00,0.00,0.01,0.0,0.01
642,16545,Mario & Luigi: Paper Jam & Mario Kart 7 Double...,3DS,2015.0,Misc,Nintendo,0.00,0.00,0.01,0.0,0.01
643,16570,Fujiko F. Fujio Characters: Great Assembly! Sl...,3DS,2014.0,Action,Namco Bandai Games,0.00,0.00,0.01,0.0,0.01
...,...,...,...,...,...,...,...,...,...,...,...
16593,16533,SÃ©bastien Loeb Rally Evo,XOne,2016.0,Racing,Milestone S.r.l,0.00,0.01,0.00,0.0,0.01
16594,16534,Hitman (2016),XOne,2016.0,Action,Square Enix,0.00,0.01,0.00,0.0,0.01
16595,16565,Mighty No. 9,XOne,2016.0,Platform,Deep Silver,0.01,0.00,0.00,0.0,0.01
16596,16572,Resident Evil 4 HD,XOne,2016.0,Shooter,Capcom,0.01,0.00,0.00,0.0,0.01
16597,16579,Rugby Challenge 3,XOne,2016.0,Sports,Alternative Software,0.00,0.01,0.00,0.0,0.01

In [3]:
games[(games["Publisher"] == "Atari") & (games["Genre"] == "Action")]

,Rank,Nombre,Plataforma,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
7,866,E.T.: The Extra Terrestrial,2600,1981.0,Action,Atari,1.84,0.11,0.00,0.02,1.97
17,1587,Combat,2600,NaN,Action,Atari,1.17,0.07,0.00,0.01,1.25
37,2674,Crystal Castles,2600,1983.0,Action,Atari,0.72,0.04,0.00,0.01,0.77
55,3955,Midnight Magic,2600,1983.0,Action,Atari,0.47,0.03,0.00,0.01,0.50
58,4017,Raiders of the Lost Ark,2600,1981.0,Action,Atari,0.46,0.03,0.00,0.01,0.50
66,4234,Circus Atari,2600,NaN,Action,Atari,0.43,0.03,0.00,0.00,0.46
67,4269,Gremlins,2600,1983.0,Action,Atari,0.43,0.03,0.00,0.00,0.46
70,4380,Maze Craze: A Game of Cops 'n Robbers,2600,NaN,Action,Atari,0.42,0.02,0.00,0.00,0.45
82,5066,Gravitar,2600,1982.0,Action,Atari,0.35,0.02,0.00,0.00,0.38
97,5800,Slot Machine,2600,NaN,Action,Atari,0.29,0.02,0.00,0.00,0.31
106,6318,Flag Capture,2600,NaN,Action,Atari,0.25,0.02,0.00,0.00,0.27
118,7186,Crazy Climber,2600,1981.0,Action,Atari,0.21,0.01,0.00,0.00,0.22
129,9108,Krull,2600,1982.0,Action,Atari,0.13,0.01,0.00,0.00,0.14
1072,4678,Ghostbusters: The Video Game,DS,2009.0,Action,Atari,0.26,0.12,0.00,0.04,0.41
1664,9643,Dragon Ball: Origins,DS,2008.0,Action,Atari,0.09,0.03,0.00,0.01,0.13
1668,9686,Godzilla Unleashed: Double Smash,DS,2007.0,Action,Atari,0.11,0.00,0.00,0.01,0.12
2429,13824,The Chase: Felix Meets Felicity,DS,2009.0,Action,Atari,0.04,0.00,0.00,0.00,0.04
2622,15052,Totally Spies! 2: Undercover,DS,2006.0,Action,Atari,0.01,0.01,0.00,0.00,0.02
3050,2817,Beyblade VForce: Ultimate Blader Jam,GBA,2003.0,Action,Atari,0.52,0.19,0.00,0.01,0.73
3081,3323,Dragon Ball Z: Buu's Fury,GBA,2004.0,Action,Atari,0.44,0.16,0.00,0.01,0.61
3184,5369,Driver 2 Advance,GBA,2002.0,Action,Atari,0.25,0.09,0.00,0.01,0.34
3212,5897,Yu Yu Hakusho Ghost Files: Spirit Detective,GBA,2003.0,Action,Atari,0.21,0.08,0.00,0.01,0.30
3223,6115,Dragon Ball GT: Transformation,GBA,2005.0,Action,Atari,0.20,0.08,0.00,0.01,0.28
3313,7505,Beyblade G-Revolution,GBA,2004.0,Action,Atari,0.15,0.05,0.00,0.00,0.20
3573,12707,Terminator 3: Rise of the Machines,GBA,2003.0,Action,Atari,0.04,0.02,0.00,0.00,0.06
3724,15411,Dragon Ball Z: Buu's Fury / Dragon Ball GT: Tr...,GBA,2006.0,Action,Atari,0.01,0.01,0.00,0.00,0.02
3881,4321,Enter the Matrix,GC,2003.0,Action,Atari,0.34,0.09,0.02,0.01,0.45
3999,7481,BeyBlade VForce: Super Tournament Battle,GC,2002.0,Action,Atari,0.16,0.04,0.00,0.01,0.21
4166,11535,Superman: Shadow of Apokolips,GC,2003.0,Action,Atari,0.06,0.02,0.00,0.00,0.08
5773,224,Driver 2,PS,2000.0,Action,Atari,2.36,2.10,0.02,0.25,4.73
7015,429,Enter the Matrix,PS2,2003.0,Action,Atari,1.78,1.12,0.09,0.19,3.18
7466,3464,Terminator 3: Rise of the Machines,PS2,2003.0,Action,Atari,0.28,0.22,0.00,0.07,0.58
7577,4030,The Matrix: Path of Neo,PS2,2005.0,Action,Atari,0.41,0.01,0.00,0.07,0.49
7662,4529,Ghostbusters: The Video Game,PS2,2009.0,Action,Atari,0.15,0.04,0.00,0.24,0.43
7678,4607,Superman: Shadow of Apokolips,PS2,2002.0,Action,Atari,0.21,0.16,0.00,0.05,0.42
7701,4733,The Terminator: Dawn of Fate,PS2,2002.0,Action,Atari,0.20,0.16,0.00,0.05,0.41
8138,7689,Forgotten Realms: Demon Stone,PS2,2004.0,Action,Atari,0.10,0.08,0.00,0.03,0.20
8729,12865,Marc Ecko's Getting Up: Contents Under Pressure,PS2,2006.0,Action,Atari,0.03,0.02,0.00,0.01,0.05
8850,14121,Asterix & Obelix: Kick Buttix,PS2,2004.0,Action,Atari,0.02,0.01,0.00,0.00,0.03
9902,7601,Afro Samurai,PS3,2009.0,Action,Atari,0.12,0.05,0.00,0.03,0.20
11150,8038,Ghostbusters: The Video Game,PSP,2009.0,Action,Atari,0.16,0.01,0.00,0.02,0.18
11504,12585,Mercury Meltdown,PSP,2006.0,Action,Atari,0.05,0.01,0.00,0.01,0.06
11702,14507,Downstream Panic!,PSP,2008.0,Action,Atari,0.03,0.00,0.00,0.00,0.03
13013,2362,Ghostbusters: The Video Game,Wii,2009.0,Action,Atari,0.60,0.21,0.00,0.08,0.88
13618,9026,Haunted House,Wii,2010.0,Action,Atari,0.13,0.00,0.00,0.01,0.14
14661,3195,Ghostbusters: The Video Game,X360,2009.0,Action,Atari,0.43,0.14,0.00,0.06,0.63
15003,6944,Afro Samurai,X360,2009.0,Action,Atari,0.16,0.05,0.00,0.02,0.24
15598,1681,Enter the Matrix,XB,2003.0,Action,Atari,0.72,0.43,0.01,0.04,1.20
15787,5735,The Matrix: Path of Neo,XB,2005.0,Action,Atari,0.23,0.07,0.00,0.01,0.31
15948,8771,The Terminator: Dawn of Fate,XB,2002.0,Action,Atari,0.11,0.03,0.00,0.01,0.15
15969,9077,Terminator 3: Rise of the Machines,XB,2003.0,Action,Atari,0.11,0.03,0.00,0.01,0.14
15994,9404,Superman: The Man of Steel,XB,2002.0,Action,Atari,0.10,0.03,0.00,0.00,0.13
16124,11196,Forgotten Realms: Demon Stone,XB,2004.0,Action,Atari,0.06,0.02,0.00,0.00,0.09
16164,11947,Loons: The Fight For Fame,XB,2002.0,Action,Atari,0.05,0.02,0.00,0.00,0.07

In [4]:
games[(games["Year"] == 1987) & (games["Plataforma"] == "NES")]

,Rank,Nombre,Plataforma,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
4690,252,Zelda II: The Adventure of Link,NES,1987.0,Adventure,Nintendo,2.19,0.50,1.61,0.08,4.38
4699,466,Mike Tyson's Punch-Out!!,NES,1987.0,Fighting,Nintendo,2.03,0.47,0.45,0.07,3.02
4702,603,Dragon Warrior II,NES,1987.0,Role-Playing,Enix Corporation,0.15,0.00,2.41,0.00,2.56
4705,648,Pro Wrestling,NES,1987.0,Fighting,Nintendo,0.77,0.18,1.42,0.03,2.40
4710,761,Volleyball,NES,1987.0,Sports,Nintendo,0.14,0.03,1.98,0.00,2.15
4729,1363,Pro Yakyuu Family Stadium '87,NES,1987.0,Sports,Namco Bandai Games,0.12,0.00,1.30,0.00,1.42
4736,1590,Gegege no Kitarou 2: Youkai Gundan no Chousen,NES,1987.0,Role-Playing,Namco Bandai Games,0.00,0.00,1.25,0.00,1.25
4760,2236,Castlevania II: Simon's Quest,NES,1987.0,Platform,Konami Digital Entertainment,0.45,0.06,0.42,0.00,0.93
4763,2468,Final Fantasy,NES,1987.0,Role-Playing,SquareSoft,0.32,0.00,0.52,0.00,0.84
4765,2549,Mega Man,NES,1987.0,Platform,Capcom,0.45,0.08,0.27,0.01,0.81

In [5]:
games[((games["Plataforma"] == "PS4") | (games["Plataforma"] == "Wii") | (games["Plataforma"] == "X360")) & ((games["Genre"] == "Action") | ((games["Genre"] == "Fighting") | (games["Genre"] == "Puzzle")))]

,Rank,Nombre,Plataforma,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
10441,45,Grand Theft Auto V,PS4,2014.0,Action,Take-Two Interactive,3.80,5.81,0.36,2.02,11.98
10449,237,The Last of Us,PS4,2014.0,Action,Sony Computer Entertainment,1.78,1.87,0.07,0.82,4.55
10450,244,Uncharted: The Nathan Drake Collection,PS4,2015.0,Action,Sony Computer Entertainment,1.96,1.69,0.08,0.74,4.47
10452,281,Watch Dogs,PS4,2014.0,Action,Ubisoft,1.40,1.86,0.11,0.77,4.14
10455,305,Assassin's Creed: Unity,PS4,2014.0,Action,Ubisoft,1.18,1.96,0.08,0.70,3.92
...,...,...,...,...,...,...,...,...,...,...,...
15545,16288,Root Double: Before Crime After Days,X360,2012.0,Action,Yeti,0.00,0.00,0.01,0.00,0.01
15553,16416,The Godfather (JP sales),X360,2006.0,Action,Electronic Arts,0.00,0.00,0.01,0.00,0.01
15554,16442,Shin Sangoku Musou 4 Special,X360,2005.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01
15558,16485,Dragon Ball Z for Kinect,X360,2012.0,Fighting,Namco Bandai Games,0.01,0.00,0.00,0.00,0.01
15559,16536,Metal Gear Solid HD Edition,X360,2011.0,Action,Konami Digital Entertainment,0.00,0.00,0.01,0.00,0.01

In [6]:
AlSuper = pd.read_csv("supermarket_sales.csv", low_memory=False)
AlSuper.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Rating,Payment,Date,Time,cogs,gross margin percentage,gross income
0,253-12-6086,A,Yangon,Member,Female,Sports and travel,98.40,7,34.440,$723.24,8.7,Credit card,03/12/2019,12:43:00 p. m.,688.80,4.761905,34.440
1,276-54-0879,B,Mandalay,Normal,Male,Sports and travel,97.74,4,19.548,$410.51,6.4,Ewallet,03/12/2019,07:53:00 p. m.,390.96,4.761905,19.548
2,373-14-0504,A,Yangon,Member,Female,Sports and travel,71.63,2,7.163,$150.42,8.8,Ewallet,02/12/2019,02:33:00 p. m.,143.26,4.761905,7.163
3,659-36-1684,C,Naypyitaw,Member,Male,Sports and travel,57.12,7,19.992,$419.83,6.5,Credit card,01/12/2019,12:02:00 p. m.,399.84,4.761905,19.992
4,751-15-6198,B,Mandalay,Normal,Male,Sports and travel,23.01,6,6.903,$144.96,7.9,Ewallet,01/12/2019,04:45:00 p. m.,138.06,4.761905,6.903

In [7]:
AlSuper[(AlSuper["City"] == "Yangon") & (AlSuper["Gender"] == "Male") & (AlSuper["Product line"] == "Sports and travel") & (AlSuper["Payment"] == "Credit card")]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Rating,Payment,Date,Time,cogs,gross margin percentage,gross income
8,289-15-7034,A,Yangon,Member,Male,Sports and travel,82.33,4,16.4660,$345.79,7.5,Credit card,01/11/2019,10:37:00 a. m.,329.32,4.761905,16.4660
34,541-48-8554,A,Yangon,Normal,Male,Sports and travel,60.95,9,27.4275,$575.98,6.0,Credit card,01/07/2019,12:08:00 p. m.,548.55,4.761905,27.4275
36,199-75-8169,A,Yangon,Member,Male,Sports and travel,15.81,10,7.9050,$166.01,8.6,Credit card,03/06/2019,12:27:00 p. m.,158.10,4.761905,7.9050
57,550-84-8664,A,Yangon,Normal,Male,Sports and travel,85.91,5,21.4775,$451.03,8.6,Credit card,22/03/2019,02:33:00 p. m.,429.55,4.761905,21.4775
64,828-61-5674,A,Yangon,Member,Male,Sports and travel,44.02,10,22.0100,$462.21,9.6,Credit card,20/03/2019,07:57:00 p. m.,440.20,4.761905,22.0100
142,149-61-1929,A,Yangon,Normal,Male,Sports and travel,64.19,10,32.0950,$674.00,6.7,Credit card,19/01/2019,02:08:00 p. m.,641.90,4.761905,32.0950
145,882-40-4577,A,Yangon,Member,Male,Sports and travel,67.26,4,13.4520,$282.49,8.0,Credit card,19/01/2019,03:28:00 p. m.,269.04,4.761905,13.4520
161,105-31-1824,A,Yangon,Member,Male,Sports and travel,69.52,7,24.3320,$510.97,8.5,Credit card,02/01/2019,03:10:00 p. m.,486.64,4.761905,24.3320
165,765-26-6951,A,Yangon,Normal,Male,Sports and travel,72.61,6,21.7830,$457.44,6.9,Credit card,01/01/2019,10:39:00 a. m.,435.66,4.761905,21.7830

In [8]:
AlSuper[(AlSuper["City"] == "Naypyitaw") & (AlSuper["Customer type"] == "Member") & ((AlSuper["Payment"] == "Cash") | (AlSuper["Payment"] == "Ewallet"))]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Rating,Payment,Date,Time,cogs,gross margin percentage,gross income
18,360-39-5055,C,Naypyitaw,Member,Male,Sports and travel,48.91,5,12.2275,$256.78,6.6,Cash,03/09/2019,10:17:00 a. m.,244.55,4.761905,12.2275
32,784-21-9238,C,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,$10.68,5.9,Cash,02/07/2019,02:15:00 p. m.,10.17,4.761905,0.5085
33,232-16-2483,C,Naypyitaw,Member,Female,Sports and travel,68.12,1,3.4060,$71.53,6.8,Ewallet,01/07/2019,12:28:00 p. m.,68.12,4.761905,3.4060
54,835-16-0096,C,Naypyitaw,Member,Male,Sports and travel,14.70,5,3.6750,$77.18,8.5,Ewallet,24/03/2019,01:48:00 p. m.,73.50,4.761905,3.6750
61,102-06-2002,C,Naypyitaw,Member,Male,Sports and travel,25.25,5,6.3125,$132.56,6.1,Cash,20/03/2019,05:52:00 p. m.,126.25,4.761905,6.3125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936,652-49-6720,C,Naypyitaw,Member,Female,Electronic accessories,60.95,1,3.0475,$64.00,5.9,Ewallet,18/02/2019,11:40:00 a. m.,60.95,4.761905,3.0475
941,273-84-2164,C,Naypyitaw,Member,Male,Electronic accessories,12.05,5,3.0125,$63.26,5.5,Ewallet,16/02/2019,03:53:00 p. m.,60.25,4.761905,3.0125
942,233-34-0817,C,Naypyitaw,Member,Female,Electronic accessories,98.84,1,4.9420,103.782,8.4,Cash,15/02/2019,11:21:00 a. m.,98.84,4.761905,4.9420
960,583-72-1480,C,Naypyitaw,Member,Male,Electronic accessories,37.06,4,7.4120,$155.65,9.7,Ewallet,31/01/2019,04:24:00 p. m.,148.24,4.761905,7.4120
970,325-90-8763,C,Naypyitaw,Member,Female,Electronic accessories,46.57,10,23.2850,488.985,7.6,Cash,27/01/2019,01:58:00 p. m.,465.70,4.761905,23.2850